name: Digger Pull Request Workflow

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize ]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  plan:
    name: Run digger
    runs-on: ubuntu-latest
    steps:
    - name: digger run
      uses: diggerhq/digger@feat/pass-approvers-into-access-policy
      with:
        disable-locking: true
        setup-aws: false
        aws-region: us-east-1
        digger-token: ${{ secrets.DIGGER_TOKEN }}
        digger-organisation: digger
        digger-hostname: https://cloud.digger.dev/
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DIGGER_GITHUB_TOKEN: ${{ secrets.DIGGER_GITHUB_TOKEN }}